package com.tian.blog.dto;

import lombok.Data;

@Data
public class UserDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USERNAME
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private String username;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_CREAT
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private Long gmtCreat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_MODIFIED
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PHONE
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.EMAIL
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.QQ
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private Integer qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.WECHAT
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private String wechat;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.URL
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ROLE
     *
     * @mbggenerated Fri Aug 21 15:40:34 CST 2020
     */
    private String role;


}